DROP TABLE Stocker;
DROP TABLE Substituer;
DROP TABLE Arroser;
DROP TABLE Associer;
DROP TABLE Plante;
DROP TABLE Espèce;
DROP TABLE Nutriments;
DROP TABLE Famille;
DROP TABLE Zone_Géographique;
DROP TABLE Fiche_Arrosage;
DROP TABLE Forêt;
DROP TABLE Jardin;
DROP TABLE Emplacement;
DROP TABLE Réserve;
DROP TABLE Météo;
DROP TABLE Saison;
-- Création des tables

CREATE TABLE Réserve (
    CODE_RESERVE VARCHAR2(10) PRIMARY KEY,
    villeR VARCHAR2(50),
    paysR VARCHAR2(50),
    telephoneR VARCHAR2(10),
    emailR VARCHAR2(60),
    nom_responsableR VARCHAR2(30)
);

CREATE TABLE Emplacement (
    CODE_EMPLACEMENT VARCHAR2(10) PRIMARY KEY,
    position VARCHAR2(100),
    CODE_RESERVE VARCHAR2(10),
    FOREIGN KEY (CODE_RESERVE) REFERENCES Réserve(CODE_RESERVE)
);

CREATE TABLE Forêt (
    CODE_EMPLACEMENT VARCHAR2(10) PRIMARY KEY,
    superficie FLOAT,
    FOREIGN KEY (CODE_EMPLACEMENT) REFERENCES Emplacement(CODE_EMPLACEMENT)
);

CREATE TABLE Jardin (
    CODE_EMPLACEMENT VARCHAR2(10) PRIMARY KEY,
    organisme VARCHAR2(100),
    adresse VARCHAR2(200),
    infosJ VARCHAR2(255),
    FOREIGN KEY (CODE_EMPLACEMENT) REFERENCES Emplacement(CODE_EMPLACEMENT)
);

CREATE TABLE Plante (
    NUM_PLANTE VARCHAR2(10) PRIMARY KEY,
    date_p DATE,
    couleur_p VARCHAR2(20),
    hauteur_p FLOAT,
    CODE_EMPLACEMENT VARCHAR2(10),
    CODE_ESPECE VARCHAR2(10),
    FOREIGN KEY (CODE_EMPLACEMENT) REFERENCES Emplacement(CODE_EMPLACEMENT),
    FOREIGN KEY (CODE_ESPECE) REFERENCES Espèce(CODE_ESPECE)
);

CREATE TABLE Espèce (
    CODE_ESPECE VARCHAR2(10) PRIMARY KEY,
    nom_scient VARCHAR2(100),
    nom_vulgaire VARCHAR2(100),
    description TEXT,
    NOM_FAMILLE VARCHAR2(50),
    FOREIGN KEY (NOM_FAMILLE) REFERENCES Famille(NOM_FAMILLE)
);

CREATE TABLE Famille (
    NOM_FAMILLE VARCHAR2(50) PRIMARY KEY,
    description_F TEXT,
    caractéristiquesF TEXT
);

CREATE TABLE Zone_Géographique (
    NOM_ZONE VARCHAR2(50) PRIMARY KEY
);

CREATE TABLE Associer (
    CODE_ESPECE VARCHAR2(10),
    NOM_ZONE VARCHAR2(50),
    PRIMARY KEY (CODE_ESPECE, NOM_ZONE),
    FOREIGN KEY (CODE_ESPECE) REFERENCES Espèce(CODE_ESPECE),
    FOREIGN KEY (NOM_ZONE) REFERENCES Zone_Géographique(NOM_ZONE)
);

CREATE TABLE Nutriments (
    CODE_NUTRIMENT VARCHAR2(10) PRIMARY KEY,
    nom_N VARCHAR2(50),
    formule_chimique VARCHAR2(100),
    type_N VARCHAR2(50)
);

CREATE TABLE Substituer (
    CODE_NUTRIMENT VARCHAR2(10),
    CODE_SUBSTITUT VARCHAR2(10),
    PRIMARY KEY (CODE_NUTRIMENT, CODE_SUBSTITUT),
    FOREIGN KEY (CODE_NUTRIMENT) REFERENCES Nutriments(CODE_NUTRIMENT),
    FOREIGN KEY (CODE_SUBSTITUT) REFERENCES Nutriments(CODE_NUTRIMENT)
);

CREATE TABLE Fiche_Arrosage (
    CODE_ARROSAGE VARCHAR2(10) PRIMARY KEY,
    mode_a VARCHAR2(50),
    qte_eau_hebdo FLOAT
);

CREATE TABLE Arroser (
    CODE_ARROSAGE VARCHAR2(10),
    HUMIDITE FLOAT,
    TEMP_MOY FLOAT,
    ajustements TEXT,
    PRIMARY KEY (CODE_ARROSAGE),
    FOREIGN KEY (CODE_ARROSAGE) REFERENCES Fiche_Arrosage(CODE_ARROSAGE)
);

CREATE TABLE Météo (
    TX_HUMIDITE FLOAT,
    TEMP_MOY FLOAT,
    NOM_SAISON VARCHAR2(50),
    PRIMARY KEY (NOM_SAISON)
);

CREATE TABLE Saison (
    NOM_SAISON VARCHAR2(50) PRIMARY KEY
);

CREATE TABLE Stocker (
    CODE_RESERVE VARCHAR2(10),
    CODE_NUTRIMENT VARCHAR2(10),
    qte_stock FLOAT,
    PRIMARY KEY (CODE_RESERVE, CODE_NUTRIMENT),
    FOREIGN KEY (CODE_RESERVE) REFERENCES Réserve(CODE_RESERVE),
    FOREIGN KEY (CODE_NUTRIMENT) REFERENCES Nutriments(CODE_NUTRIMENT)
);
